/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecensioniRouteImport } from './routes/recensioni'
import { Route as IndexRouteImport } from './routes/index'

const RecensioniRoute = RecensioniRouteImport.update({
  id: '/recensioni',
  path: '/recensioni',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recensioni': typeof RecensioniRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recensioni': typeof RecensioniRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recensioni': typeof RecensioniRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/recensioni'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/recensioni'
  id: '__root__' | '/' | '/recensioni'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecensioniRoute: typeof RecensioniRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recensioni': {
      id: '/recensioni'
      path: '/recensioni'
      fullPath: '/recensioni'
      preLoaderRoute: typeof RecensioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecensioniRoute: RecensioniRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
